/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StaffSupportRouteImport } from './routes/staff/support'
import { Route as StaffReportsRouteImport } from './routes/staff/reports'
import { Route as StaffListingsRouteImport } from './routes/staff/listings'
import { Route as StaffKycRouteImport } from './routes/staff/kyc'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AdminVisualBuilderRouteImport } from './routes/admin/visual-builder'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminThemeRouteImport } from './routes/admin/theme'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminListingsRouteImport } from './routes/admin/listings'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminFormsRouteImport } from './routes/admin/forms'
import { Route as AdminDealsRouteImport } from './routes/admin/deals'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminApiKeysRouteImport } from './routes/admin/api-keys'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AdminContactIndexRouteImport } from './routes/admin/contact.index'
import { Route as AdminFormsIdRouteImport } from './routes/admin/forms.$id'
import { Route as AdminContactIdRouteImport } from './routes/admin/contact.$id'
import { Route as AdminCmsPostsRouteImport } from './routes/admin/cms.posts'
import { Route as AdminCmsPagesRouteImport } from './routes/admin/cms.pages'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals.$id'
import { Route as AdminCmsPostsIndexRouteImport } from './routes/admin/cms.posts.index'
import { Route as AdminCmsPagesIndexRouteImport } from './routes/admin/cms.pages.index'
import { Route as AdminCmsPreviewIdRouteImport } from './routes/admin/cms.preview.$id'
import { Route as AdminCmsPostsIdRouteImport } from './routes/admin/cms.posts.$id'
import { Route as AdminCmsPagesIdRouteImport } from './routes/admin/cms.pages.$id'
import { Route as AuthenticatedDealsRequestsIdRouteImport } from './routes/_authenticated/deals.requests.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StaffSupportRoute = StaffSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffListingsRoute = StaffListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffKycRoute = StaffKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVisualBuilderRoute = AdminVisualBuilderRouteImport.update({
  id: '/visual-builder',
  path: '/visual-builder',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminContactIndexRoute = AdminContactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContactRoute,
} as any)
const AdminFormsIdRoute = AdminFormsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFormsRoute,
} as any)
const AdminContactIdRoute = AdminContactIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminContactRoute,
} as any)
const AdminCmsPostsRoute = AdminCmsPostsRouteImport.update({
  id: '/cms/posts',
  path: '/cms/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsPagesRoute = AdminCmsPagesRouteImport.update({
  id: '/cms/pages',
  path: '/cms/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)
const AdminCmsPostsIndexRoute = AdminCmsPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsPostsRoute,
} as any)
const AdminCmsPagesIndexRoute = AdminCmsPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsPagesRoute,
} as any)
const AdminCmsPreviewIdRoute = AdminCmsPreviewIdRouteImport.update({
  id: '/cms/preview/$id',
  path: '/cms/preview/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsPostsIdRoute = AdminCmsPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCmsPostsRoute,
} as any)
const AdminCmsPagesIdRoute = AdminCmsPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCmsPagesRoute,
} as any)
const AuthenticatedDealsRequestsIdRoute =
  AuthenticatedDealsRequestsIdRouteImport.update({
    id: '/requests/$id',
    path: '/requests/$id',
    getParentRoute: () => AuthenticatedDealsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contact': typeof AdminContactRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/kyc': typeof AdminKycRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visual-builder': typeof AdminVisualBuilderRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/kyc': typeof StaffKycRoute
  '/staff/listings': typeof StaffListingsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/support': typeof StaffSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/admin/cms/pages': typeof AdminCmsPagesRouteWithChildren
  '/admin/cms/posts': typeof AdminCmsPostsRouteWithChildren
  '/admin/contact/$id': typeof AdminContactIdRoute
  '/admin/forms/$id': typeof AdminFormsIdRoute
  '/admin/contact/': typeof AdminContactIndexRoute
  '/deals/requests/$id': typeof AuthenticatedDealsRequestsIdRoute
  '/admin/cms/pages/$id': typeof AdminCmsPagesIdRoute
  '/admin/cms/posts/$id': typeof AdminCmsPostsIdRoute
  '/admin/cms/preview/$id': typeof AdminCmsPreviewIdRoute
  '/admin/cms/pages/': typeof AdminCmsPagesIndexRoute
  '/admin/cms/posts/': typeof AdminCmsPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/kyc': typeof AdminKycRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visual-builder': typeof AdminVisualBuilderRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/kyc': typeof StaffKycRoute
  '/staff/listings': typeof StaffListingsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/support': typeof StaffSupportRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/admin/contact/$id': typeof AdminContactIdRoute
  '/admin/forms/$id': typeof AdminFormsIdRoute
  '/admin/contact': typeof AdminContactIndexRoute
  '/deals/requests/$id': typeof AuthenticatedDealsRequestsIdRoute
  '/admin/cms/pages/$id': typeof AdminCmsPagesIdRoute
  '/admin/cms/posts/$id': typeof AdminCmsPostsIdRoute
  '/admin/cms/preview/$id': typeof AdminCmsPreviewIdRoute
  '/admin/cms/pages': typeof AdminCmsPagesIndexRoute
  '/admin/cms/posts': typeof AdminCmsPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRouteWithChildren
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contact': typeof AdminContactRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/kyc': typeof AdminKycRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visual-builder': typeof AdminVisualBuilderRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/kyc': typeof StaffKycRoute
  '/staff/listings': typeof StaffListingsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/support': typeof StaffSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/_authenticated/deals/$id': typeof AuthenticatedDealsIdRoute
  '/admin/cms/pages': typeof AdminCmsPagesRouteWithChildren
  '/admin/cms/posts': typeof AdminCmsPostsRouteWithChildren
  '/admin/contact/$id': typeof AdminContactIdRoute
  '/admin/forms/$id': typeof AdminFormsIdRoute
  '/admin/contact/': typeof AdminContactIndexRoute
  '/_authenticated/deals/requests/$id': typeof AuthenticatedDealsRequestsIdRoute
  '/admin/cms/pages/$id': typeof AdminCmsPagesIdRoute
  '/admin/cms/posts/$id': typeof AdminCmsPostsIdRoute
  '/admin/cms/preview/$id': typeof AdminCmsPreviewIdRoute
  '/admin/cms/pages/': typeof AdminCmsPagesIndexRoute
  '/admin/cms/posts/': typeof AdminCmsPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/staff'
    | '/$slug'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/crm'
    | '/dashboard'
    | '/deals'
    | '/help'
    | '/kyc'
    | '/listings'
    | '/marketplace'
    | '/notifications'
    | '/settings'
    | '/subscription'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/contact'
    | '/admin/dashboard'
    | '/admin/deals'
    | '/admin/forms'
    | '/admin/kyc'
    | '/admin/listings'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/system'
    | '/admin/theme'
    | '/admin/users'
    | '/admin/visual-builder'
    | '/admin/webhooks'
    | '/blog/$slug'
    | '/staff/dashboard'
    | '/staff/kyc'
    | '/staff/listings'
    | '/staff/reports'
    | '/staff/support'
    | '/admin/'
    | '/staff/'
    | '/deals/$id'
    | '/admin/cms/pages'
    | '/admin/cms/posts'
    | '/admin/contact/$id'
    | '/admin/forms/$id'
    | '/admin/contact/'
    | '/deals/requests/$id'
    | '/admin/cms/pages/$id'
    | '/admin/cms/posts/$id'
    | '/admin/cms/preview/$id'
    | '/admin/cms/pages/'
    | '/admin/cms/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/crm'
    | '/dashboard'
    | '/deals'
    | '/help'
    | '/kyc'
    | '/listings'
    | '/marketplace'
    | '/notifications'
    | '/settings'
    | '/subscription'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/deals'
    | '/admin/forms'
    | '/admin/kyc'
    | '/admin/listings'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/system'
    | '/admin/theme'
    | '/admin/users'
    | '/admin/visual-builder'
    | '/admin/webhooks'
    | '/blog/$slug'
    | '/staff/dashboard'
    | '/staff/kyc'
    | '/staff/listings'
    | '/staff/reports'
    | '/staff/support'
    | '/admin'
    | '/staff'
    | '/deals/$id'
    | '/admin/contact/$id'
    | '/admin/forms/$id'
    | '/admin/contact'
    | '/deals/requests/$id'
    | '/admin/cms/pages/$id'
    | '/admin/cms/posts/$id'
    | '/admin/cms/preview/$id'
    | '/admin/cms/pages'
    | '/admin/cms/posts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/staff'
    | '/$slug'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/deals'
    | '/_authenticated/help'
    | '/_authenticated/kyc'
    | '/_authenticated/listings'
    | '/_authenticated/marketplace'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/contact'
    | '/admin/dashboard'
    | '/admin/deals'
    | '/admin/forms'
    | '/admin/kyc'
    | '/admin/listings'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/system'
    | '/admin/theme'
    | '/admin/users'
    | '/admin/visual-builder'
    | '/admin/webhooks'
    | '/blog/$slug'
    | '/staff/dashboard'
    | '/staff/kyc'
    | '/staff/listings'
    | '/staff/reports'
    | '/staff/support'
    | '/admin/'
    | '/staff/'
    | '/_authenticated/deals/$id'
    | '/admin/cms/pages'
    | '/admin/cms/posts'
    | '/admin/contact/$id'
    | '/admin/forms/$id'
    | '/admin/contact/'
    | '/_authenticated/deals/requests/$id'
    | '/admin/cms/pages/$id'
    | '/admin/cms/posts/$id'
    | '/admin/cms/preview/$id'
    | '/admin/cms/pages/'
    | '/admin/cms/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/staff/support': {
      id: '/staff/support'
      path: '/support'
      fullPath: '/staff/support'
      preLoaderRoute: typeof StaffSupportRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/listings': {
      id: '/staff/listings'
      path: '/listings'
      fullPath: '/staff/listings'
      preLoaderRoute: typeof StaffListingsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/kyc': {
      id: '/staff/kyc'
      path: '/kyc'
      fullPath: '/staff/kyc'
      preLoaderRoute: typeof StaffKycRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/visual-builder': {
      id: '/admin/visual-builder'
      path: '/visual-builder'
      fullPath: '/admin/visual-builder'
      preLoaderRoute: typeof AdminVisualBuilderRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/contact/': {
      id: '/admin/contact/'
      path: '/'
      fullPath: '/admin/contact/'
      preLoaderRoute: typeof AdminContactIndexRouteImport
      parentRoute: typeof AdminContactRoute
    }
    '/admin/forms/$id': {
      id: '/admin/forms/$id'
      path: '/$id'
      fullPath: '/admin/forms/$id'
      preLoaderRoute: typeof AdminFormsIdRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/admin/contact/$id': {
      id: '/admin/contact/$id'
      path: '/$id'
      fullPath: '/admin/contact/$id'
      preLoaderRoute: typeof AdminContactIdRouteImport
      parentRoute: typeof AdminContactRoute
    }
    '/admin/cms/posts': {
      id: '/admin/cms/posts'
      path: '/cms/posts'
      fullPath: '/admin/cms/posts'
      preLoaderRoute: typeof AdminCmsPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/pages': {
      id: '/admin/cms/pages'
      path: '/cms/pages'
      fullPath: '/admin/cms/pages'
      preLoaderRoute: typeof AdminCmsPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/deals/$id': {
      id: '/_authenticated/deals/$id'
      path: '/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/admin/cms/posts/': {
      id: '/admin/cms/posts/'
      path: '/'
      fullPath: '/admin/cms/posts/'
      preLoaderRoute: typeof AdminCmsPostsIndexRouteImport
      parentRoute: typeof AdminCmsPostsRoute
    }
    '/admin/cms/pages/': {
      id: '/admin/cms/pages/'
      path: '/'
      fullPath: '/admin/cms/pages/'
      preLoaderRoute: typeof AdminCmsPagesIndexRouteImport
      parentRoute: typeof AdminCmsPagesRoute
    }
    '/admin/cms/preview/$id': {
      id: '/admin/cms/preview/$id'
      path: '/cms/preview/$id'
      fullPath: '/admin/cms/preview/$id'
      preLoaderRoute: typeof AdminCmsPreviewIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/posts/$id': {
      id: '/admin/cms/posts/$id'
      path: '/$id'
      fullPath: '/admin/cms/posts/$id'
      preLoaderRoute: typeof AdminCmsPostsIdRouteImport
      parentRoute: typeof AdminCmsPostsRoute
    }
    '/admin/cms/pages/$id': {
      id: '/admin/cms/pages/$id'
      path: '/$id'
      fullPath: '/admin/cms/pages/$id'
      preLoaderRoute: typeof AdminCmsPagesIdRouteImport
      parentRoute: typeof AdminCmsPagesRoute
    }
    '/_authenticated/deals/requests/$id': {
      id: '/_authenticated/deals/requests/$id'
      path: '/requests/$id'
      fullPath: '/deals/requests/$id'
      preLoaderRoute: typeof AuthenticatedDealsRequestsIdRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
  }
}

interface AuthenticatedDealsRouteChildren {
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRoute
  AuthenticatedDealsRequestsIdRoute: typeof AuthenticatedDealsRequestsIdRoute
}

const AuthenticatedDealsRouteChildren: AuthenticatedDealsRouteChildren = {
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRoute,
  AuthenticatedDealsRequestsIdRoute: AuthenticatedDealsRequestsIdRoute,
}

const AuthenticatedDealsRouteWithChildren =
  AuthenticatedDealsRoute._addFileChildren(AuthenticatedDealsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRouteWithChildren
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRouteWithChildren,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminContactRouteChildren {
  AdminContactIdRoute: typeof AdminContactIdRoute
  AdminContactIndexRoute: typeof AdminContactIndexRoute
}

const AdminContactRouteChildren: AdminContactRouteChildren = {
  AdminContactIdRoute: AdminContactIdRoute,
  AdminContactIndexRoute: AdminContactIndexRoute,
}

const AdminContactRouteWithChildren = AdminContactRoute._addFileChildren(
  AdminContactRouteChildren,
)

interface AdminFormsRouteChildren {
  AdminFormsIdRoute: typeof AdminFormsIdRoute
}

const AdminFormsRouteChildren: AdminFormsRouteChildren = {
  AdminFormsIdRoute: AdminFormsIdRoute,
}

const AdminFormsRouteWithChildren = AdminFormsRoute._addFileChildren(
  AdminFormsRouteChildren,
)

interface AdminCmsPagesRouteChildren {
  AdminCmsPagesIdRoute: typeof AdminCmsPagesIdRoute
  AdminCmsPagesIndexRoute: typeof AdminCmsPagesIndexRoute
}

const AdminCmsPagesRouteChildren: AdminCmsPagesRouteChildren = {
  AdminCmsPagesIdRoute: AdminCmsPagesIdRoute,
  AdminCmsPagesIndexRoute: AdminCmsPagesIndexRoute,
}

const AdminCmsPagesRouteWithChildren = AdminCmsPagesRoute._addFileChildren(
  AdminCmsPagesRouteChildren,
)

interface AdminCmsPostsRouteChildren {
  AdminCmsPostsIdRoute: typeof AdminCmsPostsIdRoute
  AdminCmsPostsIndexRoute: typeof AdminCmsPostsIndexRoute
}

const AdminCmsPostsRouteChildren: AdminCmsPostsRouteChildren = {
  AdminCmsPostsIdRoute: AdminCmsPostsIdRoute,
  AdminCmsPostsIndexRoute: AdminCmsPostsIndexRoute,
}

const AdminCmsPostsRouteWithChildren = AdminCmsPostsRoute._addFileChildren(
  AdminCmsPostsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContactRoute: typeof AdminContactRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminFormsRoute: typeof AdminFormsRouteWithChildren
  AdminKycRoute: typeof AdminKycRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVisualBuilderRoute: typeof AdminVisualBuilderRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCmsPagesRoute: typeof AdminCmsPagesRouteWithChildren
  AdminCmsPostsRoute: typeof AdminCmsPostsRouteWithChildren
  AdminCmsPreviewIdRoute: typeof AdminCmsPreviewIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminContactRoute: AdminContactRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminFormsRoute: AdminFormsRouteWithChildren,
  AdminKycRoute: AdminKycRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVisualBuilderRoute: AdminVisualBuilderRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCmsPagesRoute: AdminCmsPagesRouteWithChildren,
  AdminCmsPostsRoute: AdminCmsPostsRouteWithChildren,
  AdminCmsPreviewIdRoute: AdminCmsPreviewIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffKycRoute: typeof StaffKycRoute
  StaffListingsRoute: typeof StaffListingsRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffSupportRoute: typeof StaffSupportRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffDashboardRoute: StaffDashboardRoute,
  StaffKycRoute: StaffKycRoute,
  StaffListingsRoute: StaffListingsRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffSupportRoute: StaffSupportRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
